[project]
name = "job-hunter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "siddheshwarkhandare", email = "235892541+siddheshwarkhandare@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "jinja2>=3.1.6",
    "pydantic>=2.13.5",
    "unicron>=0.0.1",
    "uvicorn>=0.52.4",
]

[project.scripts]
job-hunter = "job_hunter:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
